version: "3.7"

services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--username", "${MONGODB_USER}", "--password", "${MONGODB_PASSWORD}", "--eval", "'db.serverStatus().ok'"]
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf:ro
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5

  redis-gui:
    image: redislabs/redisinsight:1.11.1
    container_name: redis-gui
    ports:
      - 8001:8001

volumes:
  mongodb-data:
