version: "3.7"

services:
  api:
    image: recipes-api
    build: .
    depends_on:
      - mongodb
      - redis
      - rabbitmq
    volumes:
      - ./certs/localhost.crt:/root/certs/localhost.crt:ro
      - ./certs/localhost.key:/root/certs/localhost.key:ro
    environment:
      MONGODB_DATABASE: ${MONGODB_DATABASE}
      MONGODB_URI: ${MONGODB_URI}
      RABBITMQ_QUEUE: ${RABBITMQ_QUEUE}
      RABBITMQ_URI: ${RABBITMQ_URI}
      REDIS_URL: ${REDIS_URL}

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--username", "${MONGODB_USER}", "--password", "${MONGODB_PASSWORD}", "--eval", "'db.serverStatus().ok'"]
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf:ro
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5

  redis-gui:
    image: redislabs/redisinsight:1.11.1
    container_name: redis-gui
    ports:
      - 8001:8001

  rabbitmq:
    image: heidiks/rabbitmq-delayed-message-exchange:3.9.7-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "--quiet", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5

  worker:
    image: rss-parser-consumer
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      MONGODB_DATABASE: ${MONGODB_DATABASE}
      MONGODB_URI: ${MONGODB_URI}
      RABBITMQ_QUEUE: ${RABBITMQ_QUEUE}
      RABBITMQ_URI: ${RABBITMQ_URI}

volumes:
  mongodb-data:
  rabbitmq-data:
